export interface DayContent {
  day: number;
  hormoneHoroscope: string;
  makeTodayBetter: string;
  funFact: string;
  notes?: string; // Optional field for any specific notes like "Ovulation Day"
}

export const cycleDayContentData: DayContent[] = [
  {
    day: 1,
    hormoneHoroscope:
      "Your monthly cycle gets off to a slow start with the onset of your period, which marks Day 1 in Week 1 of your cycle. Your day could be clouded by menstrual cramps and/or fatigue that may make you wish you could cancel all your plans and just curl up on the couch with the TV remote and a hot water bottle. But, no matter what you end up doing, you'll probably want to stick close to a bathroom as the transition from your premenstrual Week 4 to your Week 1 can result in a bit of loose stool and frequent urination. Tired of all the bad news about your Day 1? Well, here's a bunch of good stuff you can look forward to today: Just a few hours after you get your period, estrogen starts to rise after having hit rock-bottom. And since rising estrogen is the exact antidote needed to conquer PMS, it signals the end of the see-sawy emotions and irritation you experienced during your premenstrual week. What a relief, right? It gets even better: Now you've got a whole two weeks of rising estrogen to look forward to-and that means a boost in mood, brain skills, energy, passion, motivation and optimism the higher this hormone climbs!",
    makeTodayBetter:
      "If you experience fatigue, mental fogginess, the blues or irritability during your period, one key culprit could be low iron due to blood loss during menstruation. Thankfully, it's easy to reverse! Simply load up on iron-rich foods (such as beans, iron-enriched cereal, lean beef, lentils, spinach and tofu) or pop an iron supplement (15 mg. for women ages 14 to 18; 18 mg. for women ages 19 to 50) every day of your cycle. This will keep your body's supply of this essential mineral from dipping too low once your period comes.",
    funFact:
      "Better keep an eye on the clock around 8 am throughout your Week 1 and Week 2. You'll likely feel as though you have more time than you really do, which can end up making you late to work, school, a doctor's appointment or an important event. That's because researchers found your hormones make your inner body clock run a little slower at this time of day during this phase of your cycle.",
  },
  {
    day: 2,
    hormoneHoroscope:
      "You're likely experiencing some of your heaviest menstrual bleeding today, which can sap your physical and mental energy, making you want to cocoon at home or a favorite relaxing spot. Despite this, you may notice that compared to the past few days, the sun is shining a little more brightly, birds are singing a little more sweetly and your boss isn't a total jerk. That's rising estrogen's influence. With the level of this hormone climbing slightly, it boosts your mood and outlook, making everything seem just a teeny tiny bit better. Oh, you may still get ticked off if someone eats the last cookie or you misplace your cell phone. But, this hormone is helping you get over problems faster and restore you to a more positive mindset. The small rise in this hormone is also making it a smidge easier to recall dates, names and other facts as it sharpens your memory. Luckily, you won't need any help remembering how to use your credit card. Spending is up as you treat yourself to silly, totally unnecessary items-like nail polish or a cupcake with rainbow sprinkles-as a way to combat period-related aches and fatigue.",
    makeTodayBetter:
      "If menstrual cramps are bugging you, try sipping chamomile tea. Researchers found that this mildly sweet herbal brew contains compounds that relax uterine muscles, easing cramp pain.",
    funFact:
      "Research shows that during your period you excel at projects requiring spatial skills (the kind that allow you to rotate images in your head, say, when planning a new room layout or assembling a lamp). Why? When estrogen is low, it allows your testosterone to dominate- and this is a hormone that improves your spatial skill ability. Thought only men have testosterone? Nope! Women's bodies also make this hormone, though in much smaller amounts. And, it's a good thing we do, too, since testosterone helps rev your brain skills, mood, energy and romantic feelings.",
  },
  {
    day: 3,
    hormoneHoroscope:
      "You may have that \"Ahhh, finally!\" feeling today as estrogen rises to a point that noticeably lifts your pep and makes you laugh more easily than you have in days. You'll also find that your memory is getting a bit sharper and you're thinking faster on your feet. And that's not the only thing happening in your brain: Your thoughts are turning more to secret crushes or the affection you have for your current squeeze. That's because rising estrogen is pushing you to make a love connection and has you focusing more on your sweetie's strengths and overlooking any faults. A boost in optimism also makes problems you've been facing seem easier to overcome. Or at least easier to sweep under the rug and ignore for now. You may notice you're not reaching for chips, cookies and other junk foods as frequently today as you did in the past two weeks as estrogen decreases food cravings and reduces your appetite slightly. But, watch your wallet: You can become more susceptible to impulse purchases, putting fun little doodads and knick-knacks in your basket along with practically anything else store owners have wisely placed next to the cash register. However, if you have a clear savings goal you're striving for (such as saving up to take a class) and you think about it when you're tempted to splurge, this same hormone helps rev your willpower, making it easier to conserve your cash.",
    makeTodayBetter:
      "If you're bothered by menstrual cramps, try gently rubbing your lower abdomen with massage oil that contains fragrant essential oils, such as rose, lavender and clary sage, for about 10 minutes. Research shows this eases cramp pain likely by nixing stress, reducing inflammation and relaxing spasming uterine muscles.",
    funFact:
      "Believe it or not, a little stress-say, from a tight deadline or taking a test-makes you smarter during your period! Researchers chalk it up to a combination of the mood boost you get from rising estrogen with the excitement you get from facing a high-pressure situation, which work together to sharpen brain skills.",
  },
  {
    day: 4,
    hormoneHoroscope:
      "By today, estrogen has likely risen to a point where you're noticing a significant surge in physical and mental energy. For some, this power-boost may be a bit too much, causing antsiness or anxiety. However, this should subside as your body gets used to the extra pep. If you want help taking the edge off, try using calming techniques, such as yoga, meditation, progressive muscle relaxation, slow breathing or taking a walk outdoors. Along with your energy level, your mood, confidence, desire to socialize, flirt and chat up a storm all increase, too. You're probably thinking about plans, goals and projects you'd like to tick off your (ever-growing) to-do list. If you've been considering pursuing a health-boosting goal-such as exercising more, cutting back on fattening foods or quitting smoking-add that to your list of tasks today, too. The middle of your Week 1 is perfect for starting a healthy new habit because rising estrogen is amping up your motivation, stick-to-itiveness and desire to improve your life. Even better, this helpful hormone is reducing pain, cravings and other bothersome symptoms that can come from making a big lifestyle change.",
    makeTodayBetter:
      "Not feeling a noticeable lift in energy from rising hormones? You may be low in iron due to menstruation. If you haven't been replenishing this key pep-boosting mineral with iron-rich foods or by taking an iron supplement since the start of your period, start doing so ASAP. And if you have been replenishing your iron since your period began, continue to do so.",
    funFact:
      "During Week 1 and Week 2 of your cycle, you're better at figuring out what people are feeling just by looking at their facial expressions and body language. Researchers speculate it may be because rising estrogen is pushing you to make more social connections, so your brain sharpens this skill during these cycle weeks to help make communication easier.",
  },
  {
    day: 5,
    hormoneHoroscope:
      "Thanks to rising estrogen, you're doing everything a little faster, like talking, driving, biking, texting and zipping your shopping cart past slow-pokes in the grocery aisle who shake an angry fist at you as you race by. But, at least you'll be flashing them a big smile as they complain. That's because your mood is brighter and it takes a lot more for anything to get you irritated or down. You may find yourself daydreaming about ways to have some intense fun-such as traveling or visiting an amusement park-as rising estrogen makes you bored with the same old hum-drum routine and pushes you to try something new and exciting. Speaking of excitement, this hormone is also urging you to fill up your calendar with hot dates with a new love or romantic rendezvous with your current one. And it's a great time to do so: You're speaking eloquently and your brain skills are sharp, making it easy for you to charm just about anyone.",
    makeTodayBetter:
      "If you want a bump in pay or a better price on something you're purchasing, aim to ask for it from today through the end of Week 2 of your cycle. Estrogen rises to levels that make you confident and well-spoken-traits that make you more persuasive so you can talk your way into getting exactly what you want.",
    funFact:
      "Careful! From today through the end of your Week 2, you're more likely to get hooked on caffeine, cigarettes, gambling and other \"baddies\" that give you a rush. Blame goes to rising estrogen, which triggers a bigger reward sensation in the brain, making you want to experience that rush again and again. So, keep this tidbit in mind the next time you're doing something that could potentially drain your wallet or impact your health-like buying scratch-off lottery tickets or eating deep-fried Oreos!",
  },
  {
    day: 6,
    hormoneHoroscope:
      "You could end up annoying grouches today with your tendency to look for a silver lining in just about anything as rising estrogen buoys your mood and keeps a smile on your face. This hormone Is also making you more curious and inquisitive about the world around you, so you may search for a class where you can learn something new, read more news websites or simply catch up on the latest gossip from pals. You're more optimistic today, which could have you splurging (after all, you'll figure out how to pay the bill somehow!) or saying \"yes\" to a big favor (how hard could it be to help a friend move, right?). You enjoy socializing more now, so you could feel a bit bored or lonely if you end up spending the day by yourself. Besides, you're putting more time and effort into your clothes, hair and other aspects of your appearance, so it would be a shame if no friends or love interests were around to dole out compliments to you!",
    makeTodayBetter:
      "Make plans to do a big, exciting activity over the next few days, like attending a party or going rock climbing. Rising estrogen has you craving a thrill all the way through the end of Week 2. So, you could be filled with regret if you don't schedule something exhilarating for this super-fun phase.",
    funFact:
      "During your Week 1 and Week 2, you may notice more of your dreams have an upbeat storyline or involve romance. Thanks goes to rising estrogen, which lifts your mood and desire for love during the day, which then affects your dream content at night.",
  },
  {
    day: 7,
    hormoneHoroscope:
      "You'll likely be more passionate about ideas, a big project, love interest, hobby or even just a great sale today due to rising estrogen, which makes you more easily excited. And because you're in a talkative mood, you're more than happy to share the details of your passion with friends, family and anyone within a 25-foot radius. It will probably be pretty easy for others to pick up on your enthusiasm: Rising estrogen has you speaking a bit louder, using more dramatic gestures and is making you appear more energetic overall. This hormone is also boosting brain skills that make learning easier. You're absorbing and comprehending new information like a sponge, which makes it a great day to try a new software program, watch a webinar or figure out complex instructions. Getting dressed for your day or a fabulous night out is more fun since your self-confidence is climbing high, so experiment with a new outfit or hairstyle. You may also spontaneously dole out compliments to friends, family and even strangers on their appearance thanks to elevated estrogen, which is boosting your mood and giving you the urge to spread the good feelings to others.",
    makeTodayBetter:
      "Treat yourself to food or beverages with complex or unusual ingredients. Rising estrogen is sharpening your senses of taste and smell, so you're better at detecting and appreciating subtle flavors all through the end of your Week 2.",
    funFact:
      "Health experts consider today the best time of your monthly cycle to do a breast self-exam-an important method for finding breast cancer in its early, most treatable stage.",
  },
  {
    day: 8,
    hormoneHoroscope:
      "Welcome to Week 2 of your monthly cycle-by far, most women's favorite week. And for good reason! Now is when your mood, energy, brain skills, confidence and excitement peak thanks to higher levels of estrogen and testosterone. You're more outgoing and comfortable being the center of attention, so you're likely dressing to impress and looking for opportunities to spend time with pals or meet new people. Your longing for romance and intimacy soars, so you're probably pursuing a new love or chasing down the one you already have. And the pay-off for doing so is big: High estrogen and testosterone (a hormone that revs desire and intensifies pleasurable sensations) are producing more sparks and tingles whenever you kiss and cuddle. When shopping, you're gravitating toward high-priced and luxury items and, because of high hormones that boost your optimism, you're likely not too worried about the cost. Looking for a brilliant plan for a project or ways to fix a nagging problem? Brainstorm today through the end of your Week 2. Research shows you come up with more creative, out-of-the-box ideas during this phase of your cycle because you're thinking faster on your feet and are less critical of unconventional solutions you come up with. One word of warning: Rising estrogen can trigger a bit of anxiety when facing tense situations, so when you feel stress start to climb, be ready to use relaxation-inducers, such as slow breathing, sipping chamomile tea or picturing your happy place.",
    makeTodayBetter:
      "Not feeling the surge in energy and mood you should? Then consider it a red flag that something's out of whack-maybe too little sleep, too much stress or a poor diet. Once you fix the problem, you'll be enjoying high-hormone pep and good feelings once again.",
    funFact:
      "Estrogen is making your face more beautiful now through the end of your Week 2 by giving your skin a healthy glow and making your features more symmetrical and feminine. This makes it a great time to take a new photo of yourself and post it to your online profile!",
  },
  {
    day: 9,
    hormoneHoroscope:
      "Hemlines go up, necklines go down and you're likely wearing more makeup, jewelry and/or accessories as estrogen pushes you to show off your physical beauty. This same hormone is also making your excitement and optimism bubble over. While that's usually a good thing, it can also mean you may not be taking necessary precautions for instance, you may be convinced you're head over heels in love with someone you just met, you could be easily talked into doing zany things by wacky pals or you're more easily persuaded to buy an expensive totally out-of-your-budget item by a fast-talking salesperson. So, try to pause before impulsively jumping head-first into something that could be difficult to back out of. If you've got a big project to tackle, now's the time to get crackin'. With your memory, brain skills and energy all super-high, you can make serious progress on it. But, don't forget to fit in fun-time, too, since too many hours stuck behind a desk can make you restless today. You're up for adventure and trying something new, so you'll enjoy shaking up your routine, for example, by attending a fun event or sampling a different type of cuisine than you usually eat.",
    makeTodayBetter:
      "Want someone to agree to a favor, for instance, to help you with a project or let you borrow something? Go ahead and ask now. High estrogen is making you more persuasive by boosting your confidence, energy and verbal skills. Plus, it's sharpening your memory, so you remember all the many reasons why you deserve to hear a \"yes\"!",
    funFact:
      "Something interesting happens to your voice in Week 2: High estrogen has you using a wider range of high and low notes as you speak and is making you sound more feminine and attractive. This makes it a perfect day to record a new voicemail greeting or call up a cutie for a date.",
  },
  {
    day: 10,
    hormoneHoroscope:
      "Your high estrogen-fueled optimism could make you feel luckier today, so you may enter games of chance-say, buying a lottery ticket or signing up for a contest-because you feel your odds of winning are greater. You're also feeling luckier in love. So, if you're single, you may head out to a party or sign up for an online dating website in the hopes of finding someone new. If you're happily hitched, you may corral your cutie into joining you on a romantic date. Regardless of your relationship status, as you approach the end of your Week 2, you become more attracted to dominant, confident, assertive hotties and those in positions of power, either at their workplace or in their sports league or social circle. You're also drawn to those with more symmetrical features and who are total flirts. And with estrogen so high, you're confident enough to flirt right back! This surge in confidence also makes you an excellent leader, able to make decisions in a flash. And folks are happy to follow you. That's because your high hormones are making you appear like a person in charge by making you more extroverted, improving your eloquence and prompting you to come up with brilliant ideas.",
    makeTodayBetter:
      "Misplaced something, like your keys or a favorite hat? Try to find it during your Week 2. High estrogen is pushing your memory into superpowers territory. So, taking a few moments to think back to when you last had the item could help you recall exactly where it is.",
    funFact:
      "Research shows your tongue-twister skills peak in your Week 2 thanks to high estrogen. Here, try it for yourself: Say \"Irish wristwatch, Swiss wristwatch\", \"A proper copper coffee pot\" or \"She sells seashells by the seashore\" three times fast!",
  },
  {
    day: 11,
    hormoneHoroscope:
      "If you've got a dentist appointment, bikini waxing or other painful procedure to undergo, schedule it to fall during your Week 2. High estrogen is blunting pain sensations, making whatever ouch-inducer less uncomfortable now than during any other time of your cycle. High estrogen has other interesting effects on you, too: For instance, it's making you talk faster (you might want to slow down around the men-folk since they could have trouble keeping up), it's got you crushing hard on your sweetie or someone new (and overlooking even their worst faults, like an undying love of polka music) and it's making you spend more on cosmetics, clothes, jewelry and other items that boost your beauty (unless you have a clear savings goal in mind, in which case it then helps bolster your willpower to save). Soaring hormones also have your brain working super-fast (this goes double after any caffeinated whatever-cino you drink) so you're thinking up lots of ideas, plans and goals. And, being as ambitious as you are right now, you're probably getting started on at least one (or two or five) of them today.",
    makeTodayBetter:
      "High hormones make you enjoy being challenged and surprised, so you'll love learning a new skill, listening to an unfamiliar type of music, trying an exotic food or doing anything that's new, new, new!",
    funFact:
      "The way you walk and dance drive cuties around you crazy right now. Research shows that high estrogen is making subtle changes to the way you move your body that boost your attractiveness.",
  },
  {
    day: 12,
    hormoneHoroscope:
      "Heads up, Week 2 gal: This phase of your cycle only comes around once, so take advantage of your high energy, great mood, sharpened brain skills and intense passion while it's here! For instance, plan a night out with pals, launch a new business or try a new workout routine. You'll also enjoy anything where romance is involved, say, a hot date with your darling or a singles event filled with physically strong and confident cuties who are on a top rung of their corporate, athletic or social ladder since that's the type high estrogen is pushing you toward right now. Keep in mind that soaring levels of this hormone are also making you more easily won over by sweet-talking salespeople and persuasive pals who need a favor. So, take a moment to pause before agreeing to anything or signing on the dotted line. You're likely wearing more colorful, form-fitting outfits and taking more time to get your hair and makeup just right. Since you tend to get a bit bored with the way you've done things a million times before, you may suddenly decide to make a big change to your appearance, for instance, by switching your hair color or revamping your fashion style. Whatever you do today, remember that, despite all its wonderful benefits, high estrogen can prompt a bit of anxiety. Therefore, be ready to use soothing tension-tamers in case you need them, such as going for a relaxing walk or meditating.",
    makeTodayBetter:
      "Wash your hands and/or use antibacterial gel more frequently during the second half of your Week 2. You're more susceptible to cold and flu viruses because high estrogen is weakening your immune system and thinning mucus in your nose and eyes, which means it's easier for germs to pass through and grab hold. On the upside, this mucus-thinning effect also makes the second half of your Week 2 the best days to get your Pap smear.",
    funFact:
      "You can ditch the perfume from today through the end of your Week 2 because you won't need it. Your body is churning out lots of come-hither pheromones-scentless chemicals that attract hotties like a magnet!",
  },
  {
    day: 13,
    notes: "Ovulation Day! (Predicted)",
    hormoneHoroscope:
      "Okay, so you know that feeling you get when you're on the first part of a rollercoaster as the cars are slowly climbing up, up, up? You're excited, thrilled, happy. And when you get to the very top, the cars pause and you're so high you can see out across the whole amusement park and it's just beautiful and awesome? And then-boom!-you drop really fast and you start screaming and wish you could get off this crazy thing? Well, today you're paused at the top of the hormone rollercoaster. So, enjoy the last bit of high estrogen and testosterone happiness, pep, chattiness, confidence, passion and brain sharpness before tomorrow hits and-boom!-your hormones drop really fast and you'll want off this crazy thing. Do all the activities your high hormones make you best at: Hang out with your buds, go on a hot date, head to a cool store, work on a pet project, master a new skill or take an impromptu day trip somewhere exciting. You'll be glad you got it in just under the wire! (Note: The Hormone Horoscope Cycle Calendar should never be used to help you avoid pregnancy.)",
    makeTodayBetter:
      "Do something that requires a lot of confidence that you've been putting off, like summoning the nerve to saying \"Hi\" to a cutie you've been eyeing or officially turning your hobby into a business. Today is the last day of your cycle that your confidence will be super-high-and you'll probably kick yourself if you end up having to wait another three weeks to give it a try.",
    funFact:
      "Wish you could lengthen Week 2 of your cycle so you can enjoy the incredible effects of rising estrogen longer? Try adopting a low-fat diet where fat makes up about 20% of your total calories. In one study, women who did just this tacked on an extra two whole days to this super-awesome week! While the researchers don't have a clear explanation why this tactic works, they point out that food intake, dietary fat and body weight can all have a direct influence on the length and regularity of your menstrual cycle. Just be sure to not go lower than a 20% fat intake since your brain, body and hormones require dietary fat to function optimally.",
  },
  {
    day: 14,
    hormoneHoroscope:
      "Welcome to Week 3 of your cycle! Things are going to be a bit different than the first two weeks you experienced. For starters, during the first half of your Week 3, levels of estrogen and testosterone nosedive, which can trigger \"pre-PMS\"-a shorter, less intense version of PMS that occurs in your premenstrual Week 4. Not many women realize that estrogen drops not once, but twice, every cycle. And both of these drops can cause a bit of irritability or the blues. On top of that, now progesterone is rising. And this sedating hormone has you feeling sleepy, quiet, less interested in socializing and more likely to prefer familiar people and surroundings over anything new. Progesterone is also revving your appetite and triggering cravings for fatty, salty, sweet and/or carb-rich foods. You may notice that passionate feelings you had for someone special in your Week 2 fade into the background this week as you turn your attention inward and start examining your own life, past choices and future decisions you need to make. And, while high adventure-loving estrogen and testosterone made you eager to let out your inner wild child last week, this week lower levels of these hormones combined with safety-preferring progesterone make you more cautious. For instance, you may slow down as you drive and bike or avoid hanging out in places where the exit signs aren't clearly marked.",
    makeTodayBetter:
      "Keep healthy snacks-like sunflower seeds, yogurt or low-fat granola bars-nearby throughout Week 3 and Week 4 of your cycle. Progesterone amps up hunger and can make some women more sensitive to blood sugar crashes, so you could get irritable when you go a long time without eating. Nibbling a small, healthy snack between meals can keep your mood stable and the hunger crankies at bay.",
    funFact:
      "Love to exercise or want more motivation to work out? Listen to this: Your body burns up to 30% more fat when you exercise throughout your Week 3 and most of your Week 4! Researchers discovered that the combination of estrogen and progesterone makes your body more efficient at using fat as fuel on these cycle days.",
  },
  {
    day: 15,
    hormoneHoroscope:
      "While the first half of your cycle was all about changing things up and exploring the outer world, the second half is all about hunkering down and exploring the inner one. The combination of lower levels of estrogen and testosterone combined with rising progesterone is making you quieter, introspective and more in touch with your emotions than you have been in the past two weeks. The days where you dressed to impress are fading away. Instead, you prefer more comfortable outfits and are probably wearing less makeup and putting less time into doing your hair than you did in your Week 2. You may feel a bit uncomfortable due to progesterone-fueled constipation, bloating and breast tenderness. And you may experience a physical and mental slow-down due to this hormone's potent sedating effect. Another thing that's slowing down? Your spending! During this week of your cycle, your credit cards get a breather as the cavalier attitude you had about finances in Week 2 gives way to worry over how you'll afford to pay all your bills. Unless, however, you see delicious treats or the perfect decorative home item. In that case, rising progesterone-which revs both your appetite and desire to \"nest\"-will push you to buy them by the dozen.",
    makeTodayBetter:
      "Beat constipation caused by progesterone with dried plums or a slice of rye bread. In separate studies, dried plums were shown to work better than over-the-counter fiber additives and rye bread better than over-the-counter laxatives at keeping you regular thanks to natural compounds in them that have a mild stool-softening effect.",
    funFact:
      "Better keep an eye on the clock around 8 pm throughout your Week 3 and Week 4. You'll likely feel as though you have more time than you really do, which can end up making you late for a date, movie or other event. That's because researchers found that your hormones make your inner body clock run a little slower at this time of the evening during this phase of your cycle.",
  },
  {
    day: 16,
    hormoneHoroscope:
      "As the first half of your Week 3 goes on, you may continue to experience a bit of pre-PMS- where the first of two drops in estrogen in your monthly cycle can trigger bouts of anger or sadness. The sharp dip in this hormone may also be chipping away at the confidence you have in your appearance and brain skills. It certainly doesn't help that rising progesterone is prompting you to retain more water than a sponge and is triggering constipation that makes you feel like you've packed on a few pounds overnight while also making you a tad foggy and forgetful. Progesterone is also being a bit pushy when it comes to your food habits, revving your desire for sweet, salty, carb-rich and/or fatty foods in abundance in case you got pregnant during ovulation and are now eating for two. Your body won't get the memo that you're not preggers till the start of Week 4, so till then you can either give in to the urge for pancakes, cookies and guacamole or distract yourself-say, with a short walk or playing a video game-till the craving passes. When making social plans, keep in mind that you'll probably be happier among a small group of friends or enjoying one-on-one time with a close pal to hanging out at a crowded venue or loud party. This doesn't mean you'll totally loathe attending a packed event. If you already have tickets for, say, a huge concert or Comic Con that falls in your Week 3, you'll still enjoy it. It just may be in a bit of a mellower way, for instance, you may opt to not throw your undies on stage at the performer this time around or perhaps you might bring just two costumes instead of your usual four.",
    makeTodayBetter:
      "If progesterone-fueled breast tenderness is bugging you, try cutting down on foods high in salt (like chips and fast food) and saturated fat (such as butter, cheese, ice cream and meat). Salt and saturated fat can increase inflammation and exacerbate water retention, worsening breast pain.",
    funFact:
      "Research shows that throughout your Week 3, you're likely washing your hands more often, using antibacterial gel, grabbing a paper towel when opening a public bathroom door, avoiding folks who are coughing or sneezing or doing other things to protect yourself from catching an illness. That's progesterone influence. As this hormone rises, it pushes you to be more careful about your health in case you got pregnant during ovulation.",
  },
  {
    day: 17,
    hormoneHoroscope:
      "Good news: At some point today, estrogen begins to climb after dropping like a stone for the past few days, putting an end to plunging-estrogen irritation and sadness you may have experienced. Once that happens, the combination of rising estrogen and progesterone will be giving you a mellow, relaxed outlook. Unless (and isn't there always an \"unless\"?) you're sensitive to progesterone, in which case, this hormone could trigger the blues or a bit of weepiness. These progesterone-fueled side effects could get even worse if you're among the many women who become more sensitive to drops in blood sugar due to this hormone. If that's the case with you, if you skip meals or go too long between meals, you could develop an intense bout of the hunger crankies that has the power to terrify people five towns away. If you can dodge all that, then this is a low-key phase where you're the calm In any storm and you're getting deeper sleep. (And that includes during the naps you're just dying to take all day thanks to sedating progesterone.) Have a big purchase or major decision to make? Today through the end of Week 3 are the best days of your whole cycle to make it. Why? The combination of rising estrogen and progesterone is making you neither overly optimistic (like you were in the first half of your cycle) nor overly pessimistic (like you'll be in the last week of your cycle). As a result, you're seeing issues in a more realistic light and are more likely to carefully weigh the pros and cons to come up with the best choice.",
    makeTodayBetter:
      "Need to shake off progesterone's groggy effects so you feel more awake while driving, studying or simply playing video games? Try chewing gum, sunflower seeds, gummy bears or anything else that gets your jaw moving. Research shows that using your jaw muscles boosts alertness and improves reaction time by stimulating certain areas of your brain.",
    funFact:
      "Have a project that requires working on lots of details, like copy editing or creating a budget? Tackle it in your Week 3. Researchers found that the sedating effects of progesterone are actually a good thing when it comes to mental focus. That's because this hormone calms your brain, which enables you concentrate better on facts, figures and other information that were too dull to zero in on during your high-energy Week 2.",
  },
  {
    day: 18,
    hormoneHoroscope:
      "You may get a serious case of the \"blahs\" today and find it difficult to muster enthusiasm about anything, like a project you're working on, great news you've heard or a cutie who's taking you out on a romantic date. That's progesterone's fault. As this sedating hormone climbs, it saps your pep and excitement. That is, unless you see a gorgeous pillow or delicious gourmet treat. In which case, this hormone-which ratchets up your urge to beautify your home and buy yummy foods by the basket-full-is making you virtually cartwheel toward the checkout counter to snap it up. You're generally not in a chatty mood today as progesterone has a quieting effect on you. And when you do pipe up, you may find that this hormone is putting a serious dent in your speaking skills, making it harder to recall the exact words you want to use and making you prone to tripping over your tongue. If you've got an important presentation or job interview where you need to be at your most eloquent, you can overcome this hormonal hurdle by simply trying to think a little longer about what you want to say before you say it. This gives your brain more time to get the words to come out just right.",
    makeTodayBetter:
      "There's no way around this: You're probably going to have more gas in your Week 3. That's because progesterone is triggering constipation, which can lead to a build-up of air in your intestines. If you feel an uncomfortable gas bubble that just won't pass, don't lie down. Research shows this tells your digestive system to slow down, trapping the air longer. Instead, stand up and walk around. This tells the digestive system to keep working, so it pushes it out faster.",
    funFact:
      "You may find yourself more easily grossed out by gory images or stinky smells throughout your Week 3. Point the blame at progesterone. Researchers speculate that this hormone increases your aversion to anything disgusting to help you steer clear of potential threats in case you got pregnant during ovulation and have a baby on board to protect. So, until your body realizes you're not pregnant at the start of Week 4, triggering a drop in progesterone, you may want to avoid stomach-churning sights and aromas.",
  },
  {
    day: 19,
    hormoneHoroscope:
      "Your body's level of sedating progesterone is rising higher and higher throughout your Week 3, which can make you more prone to zoning out and wishing you could curl up for a much-needed nap anywhere you can-under your desk, on the bus ride home, in the produce aisle nestled up to the nectarines. In fact, if someone says something super-annoying to you or that goes against everything you stand for, you might just decide to stay mum and conserve what little energy you have rather than waste your wee bit of pep trying to prove your point. While your desire for romance is on the low side, those who are most likely to win you over are sensitive, cooperative, caring types who wouldn't bat an eye if you demanded their dessert to fulfill your progesterone-fueled food cravings. Chances are, you're going to be bothered by constipation, bloat and sore breasts, which are totally normal, albeit annoying, side effects of rising progesterone. You may also find this hormone is making your brain a bit foggy and you're a tad forgetful. If you've got to work on an important project or prepare for a big test, try taking a brisk walk, listening to up-tempo music or eating a little dark chocolate. These are all study-proven ways to shake off brain fog and boost alertness in minutes.",
    makeTodayBetter:
      "Steer clear of scary movies and alarming news stories that are accompanied by graphic photos. Research shows that during the second half of your cycle, progesterone makes frightening images stick in your memory banks longer.",
    funFact:
      "You may have more negative dreams during your Week 3 and Week 4 because your hormones make you more prone to the blues, stress or worry. To up your odds of having dreams that are more positive, try placing a bowl of fragrant potpourri by your bedside (far from curious pets and children) or dabbing on your favorite essential oil before turning in. Research shows that breathing in pleasant aromas as you sleep makes you more likely to have dreams with happier storylines.",
  },
  {
    day: 20,
    hormoneHoroscope:
      "You may need to remind yourself to show more emotions today, especially when a friend surprises you with a gift or your boss gives you a raise that is, if you ever want to get one again. Rising progesterone is mellowing you out and making you quiet, so you're more likely to keep your emotions on the inside, which can confuse folks who expected a splashy show of gratitude on the outside. Because pep is so limited today, try to pinpoint the most energetic part of your day (for instance, if you're a morning, an afternoon or evening person) and get all your most important projects done during those hours. When it comes to socializing, you're apt to prefer quality one-on-one time with a best bud over attending loud, crowded parties. Some bad news for significant others: You have less interest in kissing and cuddling and more interest in snuggling up to a plate of cupcakes and bowl of chips. You could try explaining it's because of rising progesterone, a hormone that puts a damper on romantic urges while revving food cravings. But, between progesterone-fueled verbal flubs and a mouth full of cupcake, you may not get your message across too clearly.",
    makeTodayBetter:
      "Progesterone is triggering water retention throughout your Week 3 and Week 4, which can make you feel uncomfortably heavy and bloated. To the rescue: Delicious foods that act as natural mild diuretics, which include asparagus, cucumber, ginger, parsley, watercress and watermelon.",
    funFact:
      "Love the calming, soothing effects of progesterone? You can enjoy them any day of your cycle. All it takes is chatting with girlfriends or watching a romantic movie. Research shows that both activities prompt your body to produce a temporary surge in mellowing progesterone.",
  },
  {
    day: 21,
    hormoneHoroscope:
      "Your body's level of progesterone peaks today. What's this mean for you? Well, if I were you, I'd be careful of sitting on any super-comfy couches if you ever need to get back up again. That's because this hormone is making a cozy curl-up seem so much more satisfying than anything else that could possibly need your attention. You're on the quiet side today, which may be a good thing since progesterone is playing keep-away with your short-term recall and speaking abilities, which can result in some verbal blunders. When you're out and about, you may find it difficult to resist splurging in the home goods and baked goods aisles as progesterone pumps up your desire to gussy up your living space and give in to food cravings. Enjoy today's mellowness and tonight's deep sleep. Tomorrow starts your premenstrual Week 4 and, depending on your sensitivity to plunging estrogen, you may not be experiencing this level of calm or such restorative slumber again for a while.",
    makeTodayBetter:
      "Give yourself more time to get ready for work, school, appointments or social events. Progesterone is slowing you down, which can make it take a tad longer to get dressed, do your hair and prepare in other ways, causing you to run late.",
    funFact:
      "Throughout your Week 3, you prefer to spend time with family and folks from your community rather than those who are new and unfamiliar. Researchers speculate that progesterone is pushing you seek out people who are connected to you since they'll be more likely to help support and protect you in case you got pregnant during ovulation.",
  },
  {
    day: 22,
    hormoneHoroscope:
      "Did the world and all the people in it become instantly more annoying-or is it just you? It's you. Specifically, it's your plunging estrogen. Once you enter your premenstrual Week 4, plummeting levels of this hormone can trigger irritability, the blues, weepiness, and/or impatience as it drags down levels of feel-good brain chemicals. On top of that, you could be dealing with the physical side effects of nosediving estrogen-such as aches, pains, dizziness, nausea, migraine and insomnia-which can sour your mood. But, before you start hating everything about this week of your cycle, there is some good news to report: First off, you may actually feel like you have a bit more energy than you did during your Week 3. That's because progesterone is now plunging-and that's a good thing since this sedating hormone had you thisclose to face-planting into an unscheduled nap all last week. Secondly, after a week-long departure, you'll notice your romantic desire returns at some point during your Week 4 thanks to nerve endings down below getting stimulated as your body prepares for menstruation. Thirdly, you're more in touch with your emotions, which makes it a great time to pour yourself into an artistic project. And, finally, you may actually experience positive feelings! Surprised? Here's why: Premenstrual grouchiness isn't a constant. It's more likely to just pop up here and there kind of like a less fun game of Whac-A-Mole. In-between cranky moments, you tend to just be mellow and low-key. What's more, the same brain chemical that can trigger premenstrual irritation- noradrenaline-can also trigger temporary bursts of happiness. So, when you feel a sudden wave of positivity sweep over you, you can thank your premenstrual hormones!",
    makeTodayBetter:
      "Try to cut back on caffeine or at least avoid going overboard. Caffeine is known to exacerbate premenstrual irritability (especially on an empty stomach), making you more prone to losing your temper and flying off the handle.",
    funFact:
      "Research shows you're better at spotting potential danger during your Week 4, such as a car veering toward you or an open grate on the sidewalk. That's because plunging estrogen creates certain changes in the brain that make you more aware of your surroundings.",
  },
  {
    day: 23,
    hormoneHoroscope:
      "Today could be a bit see-sawy depending on your sensitivity to plunging estrogen. For instance, you could be going along fine, then someone says or does something that drives you up a wall. The problem is that when your estrogen level drops, it can make you a tad more emotionally sensitive while also bringing down your patience. It's also sapping your confidence, so worry about bills, work, school or relationships may start creeping into your thoughts, putting you on edge. Every now and then (probably more now than then), you may get hit with cravings for carbohydrate-rich treats, such as doughnuts and French fries. That's just your brain's way of trying to replenish mood-stabilizing serotonin, which dips when estrogen dips. Carbs help form this key brain chemical, giving you a temporary mood boost. (By the way, healthy carbs-such as beans, fruit, grains and vegetables-also boost serotonin in case you're into that whole \"my body is a temple\" thing.) This is so not the week to be scheduling dentist appointments, bikini waxes, breaking in new shoes or doing any other ouch-inducer since low estrogen is making pain sensations more intense than during any other week of your cycle. Also important to keep in mind: Research shows that injuries are more frequent during your premenstrual week. Blame goes to plunging estrogen, which makes you less coordinated and thus a bit clumsier. As a result, you could end up bumping into a wall, dropping a heavy item on your foot or tripping over nothing at all. Suffice it to say, texting while fire baton twirling is strongly discouraged during this time.",
    makeTodayBetter:
      "One key culprit behind a lousy premenstrual mood is even lousier sleep caused by plunging estrogen, which can trigger insomnia and nighttime restlessness. So what can you do about it? Try sipping chamomile tea a couple of hours before bedtime or doing some calming meditation before turning in to help you wind down. And make sure you nix common sleep-robbers, for instance, by airing out a stuffy bedroom, switching to sheets that aren't itchy and asking the cat to keep her overnight meowling to a minimum.",
    funFact:
      "Heads up if you've got obsessive-compulsive disorder (OCD): Research shows that OCD symptoms-for instance, washing your hands excessively, needing to perform certain \"rituals\" (like knocking three times) or having the urge to align items on your desk in a specific way-can worsen during your Week 4. Researchers theorize it may be that compulsive behaviors help you cope with anxiety or the blues caused by plunging estrogen or that a drop in serotonin during this premenstrual week triggers a rise in OCD behaviors.",
  },
  {
    day: 24,
    hormoneHoroscope:
      "It may be difficult to resist focusing on the negatives today as nosediving estrogen drags down feel-good brain chemicals, prompting a bit of pessimism. As a result, you're more likely to focus on the many, many, many faults of folks around you, such as your crush, current partner, friends, co-workers or the shoppers ahead of you in line who just seem to be breathing all wrong. Issues may also seem bigger and more difficult to overcome, filling you with fear, panic or frustration. Because of this, you may get the urge to make a major change, like quitting a job, school or relationship. However, if you can, try to put off making a drastic decision till Week 1 of your cycle rolls around when rising estrogen will be helping you see the issue in a more optimistic light. When working on a project or sitting in on a meeting, you may notice it's difficult to concentrate and that it takes a tad longer to absorb new information. However, you will discover that once you get home and onto the couch, you'll able to focus on the TV and a pint of ice cream with the greatest of ease.",
    makeTodayBetter:
      "Feeling premenstrual anger start to rise? Eat a cookie, sip lemonade or consume another food or drink with sugar. Research shows that sugar (but not sugar substitutes) eases irritation by providing the brain with the fuel it needs to rein in a fiery temper.",
    funFact:
      "Confidence can dip sharply in your Week 4, which can have negative effects on a job interview, presentation you're giving or first date. Luckily, there's an easy way to boost self-assuredness back up in minutes: Think about a steamy scene in a movie or book. Research shows that saucy thoughts prompt a surge in testosterone-a hormone that revs confidence, making you feel great about yourself!",
  },
  {
    day: 25,
    hormoneHoroscope:
      "You may feel like a bit of an absent-minded professor today: While you'll still be able to do all the things you've studied and practiced-like advanced algebra, piano concertos and reciting the Greek alphabet by heart-you're probably finding your keys in the freezer and forgetting the name of your cat. You can point a guilty finger toward plunging estrogen, which muddies up your mind a bit as it dips. This plummeting hormone is also the reason you may feel like you're coming down with a cold or other virus or you feel just plain icky. It's amping up aches and pains and making you more physically sensitive, which can trigger overall discomfort. So, it's probably a good thing you're less concerned with how other folks see you today so you can slip on your most comfortable clothes (which always seem to be the ones that are the baggiest and with the most holes) without caring what anybody thinks. Not that many folks are going to see you, anyway. During your premenstrual phase, you're happiest when close to home and sticking to familiar, nearby haunts, like a favorite café where arriving in your baggiest best is fully expected by now.",
    makeTodayBetter:
      "When anxiety, irritation or the blues are bugging you, try lighting a lavender soy candle or applying a lavender-scented essential oil to your wrists. Research shows that inhaling the fragrant essence of this flower (but not chemical smell-alikes found in some air fresheners) for 10 minutes significantly eases premenstrual negativity thanks to natural compounds that have a relaxing, mood-lifting effect on the brain.",
    funFact:
      "Dread menstrual cramps in your Week 1? You can lessen them significantly by blocking the production of prostaglandins, which are chemicals that trigger painful uterine spasms. Less prostaglandins less pain! And, good news, there are easy, study-proven ways to nix'em.\n1. Pop ibuprofen: Take one ibuprofen (such as Advil or Motrin) in the morning and one in the evening on each of the three days leading up to your period-for instance, that would be Day 26, Day 27 and Day 28 in a 28-day cycle. [Note: Never exceed the recommended dosage indicated on the label and do not take if you're allergic to aspirin.]\n2. Take fish oil: Swallow one gram of fish oil that contains both EPA and DHA on each of the three days leading up to your period. If you can't take fish oil or you're a vegetarian, take one daily micro-algae supplement with both EPA and DHA (available at health food stores) on the three days leading up to your period.\n3. Turn to vitamin E: Pop 200 IU of vitamin E twice daily (once in the morning and once at night) on the two days leading up to your period and continue during the first three days of your period.\nImportant: Always ask your doctor (or your parent if you're a minor) first before using new medicines or supplements to ensure you're not allergic or that they don't interact with a medication you're currently taking.",
  },
  {
    day: 26,
    hormoneHoroscope:
      "Careful of taking something someone says, does or posts online the wrong way. Plunging estrogen can make you a tad touchy and pessimistic-a combination that can have you jumping to the wrong conclusion and making you mistakenly believe an insult has been hurled your way. Another side effect of downward-spiraling estrogen: You may have to put up with a flare-up of a chronic condition (such as asthma, depression, digestive disorders, fibromyalgia or migraine), a bout of acne and/or \"blechyness\" in general. But, it's not all doom and gloom today: Low estrogen is also making it easier for you to channel your emotions, which is helpful when working on certain artistic projects. You're better at detecting when someone is trying to pull a fast one over on you, say, a smarmy salesperson or a credit-stealing co-worker. And you're more likely to spot danger that comes out of nowhere-like a car veering into your lane or a foul ball flying in your direction. On top of that, your desire to kiss and cuddle gets more intense as your body prepares for menstruation. In fact, some women use this rise in passion as a cue that their period is close to arriving.",
    makeTodayBetter:
      "When getting ready for work, school or an event, try sticking to an outfit you already know flatters you, a hairstyle you know how to do easily and your usual makeup routine. Plunging estrogen is prone to bringing down your confidence about your appearance while also making you more self-critical. So, trying something new and untested in this touchy week could spark a premenstrual temper flare of epic proportions when you discover the clothes don't fit right, your hair won't do what you want it to and your makeup is just flat-out wrong, bringing down your self-confidence further.",
    funFact:
      "Research shows that during your premenstrual Week 4, the combination of a little stress (say, from a tight deadline or taking a test) plus plunging estrogen amps up anxiety that can dampen your brain skills. So, when you have a challenging task to do, take a few minutes to bring down tension for instance, by taking slow breaths, going for a relaxing walk or sipping chamomile tea-so you can keep your brain skills sharp.",
  },
  {
    day: 27,
    hormoneHoroscope:
      "You'll likely be happiest today when sticking to things you know, for instance, hanging out with best buds, visiting your favorite restaurant, eating foods you've ordered a thousand times before, listening to songs you know by heart and watching re-runs on TV. That's because familiar experiences are comforting, which helps reverse a sour premenstrual mood and distracts you from low-hormone aches and discomfort. Plus, your pessimism is reaching its cycle-long high, so it's harder for new people and experiences to win you over. At times, it may seem like Murphy's Law-where anything that can go wrong will go wrong- is more like a general rule rather than an occasional happenstance today. The problem is that plummeting estrogen makes you more prone to focusing on the bad stuff rather than the good stuff, which makes the bad stuff feel like it occurs non-stop. Chances are, if you think hard enough, you may realize that there were at least a few positive things that have gone on today. And getting one day closer to your Day 1-where PMS ends and lovely mood-lifting estrogen rises-counts!",
    makeTodayBetter:
      "Take time to indulge in something fun (like a movie or a dinner with a pal who's sure to make you laugh) or do something that relaxes you (such as exercising or meditating). Research shows that activities like these reduce stress, which can ease premenstrual symptoms, including moodiness, irritability and aches. Sounds like a perfect excuse to start planning a PMS-busting activity right now!",
    funFact:
      "Watch your wallet! Research shows you tend to spend more cash during your Week 4 as a way to cope with down moods caused by plunging estrogen. To enjoy a mood-lifting premenstrual splurge without going overboard, set aside a certain amount of money you're comfortable spending on yourself that won't cause regret. Then, use it to treat yourself to something special.",
  },
  {
    day: 28,
    hormoneHoroscope:
      "This is the last day of your typical 28-day cycle. Estrogen is at its lowest point. You might be feeling premenstrual symptoms like fatigue, irritability, or cramps as your body prepares for menstruation. Reflect on the past cycle and prepare for the new one beginning tomorrow. Content for Day 28 was not explicitly detailed in the provided PDF beyond a heading.",
    makeTodayBetter:
      "Prioritize rest and self-care. Gentle stretching, a warm bath, or a cup of herbal tea can be soothing. Ensure you have menstrual products ready. If you're experiencing significant discomfort, consider pain relief options you've discussed with your doctor.",
    funFact:
      "Your body is about to reset! The end of one cycle marks the beginning of another, offering a fresh start. Tracking your symptoms and moods throughout the month can help you better understand your unique rhythm and plan accordingly.",
  },
];
